id: P691366CB
initial_creation_type: ocr
source_metadata:
  volumes:
    f2d8e556dcd848a2b2a66401c1652991:
      base_file: v037.txt
      image_group_id: I1PD95882
      title: འཇིག་རྟེན་དབང་ཕྱུག་གི་སྒྲུབ་ཐབས།
      total_pages: 1379
      volume_number: 37
